CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  consent INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
